Potsbo/fix nil problem
wantedly/github-username-converter pull request #11
Opened 2016-12-27 09:46 UTC by potsbo

## WHY

https://github.com/wantedly/developers-account-mapper/pull/7 causes build failure

## WHAT

Fix problem in user model and register command

2016-12-27 10:13 UTC, dtan4 requested changes

2016-12-27 10:13 UTC, dtan4 commented on .travis.yml
> +  - glide install
Please use apt package.
https://github.com/dtan4/s3url/blob/3f919413dd2598fc5df23c72a820182ad2b6d814/.travis.yml#L4-L8

2016-12-27 10:24 UTC, potsbo commented on .travis.yml
> +  - glide install
@dtan4 Instruction followed, thanks

2016-12-28 06:04 UTC, potsbo commented
I think it's ready

2016-12-28 06:26 UTC, dtan4 approved these changes

2016-12-28 06:26 UTC, dtan4 commented
LGTM 👍 Thank you for setting CI environment :octocat:

2016-12-28 06:26 UTC, merged