Introduce Docker
wantedly/github-username-converter pull request #32
Opened 2017-01-23 09:44 UTC by potsbo

## WHY

In some situations, running with Docker is highly maintainable.

## WHAT

- [ ] Add Dockerfile
- [ ] Update .travis.yml to push to quay
- [ ] Create required make tasks to deploy

@dtan4 
I don't know how to set the image tag, because I don't know much about Docker.
We might want to invoke `v0.2.0` or something instead of `latest`.
Then should I use `$(VERSION)` instead of `latest`?
Maybe googling for a while could lead me there, but I ask you before I get drown in the ocean...

2017-01-23 09:48 UTC, dtan4 requested changes

2017-01-23 09:48 UTC, dtan4 commented on Dockerfile
> +FROM alpine:3.4
Latest release is `alpine:3.5`.

2017-01-23 09:49 UTC, dtan4 commented
> Then should I use $(VERSION) instead of latest?

I think that both `latest` and `$(VERSION)` should be prepared. `latest` points to the latest `$(VERSION)`.

2017-01-23 09:51 UTC, dtan4 commented
By the way, I don't recommend to build Docker image in this repository together, because CI build time will be so long...
[k8sec](https://github.com/dtan4/k8sec) took about 20 minutes until tagged build had finished in the same environment.

I recommend to separate repository, e.g. `dockerfile-developers-account-mapper`. 
See this: https://github.com/dtan4/dockerfile-k8sec

2017-01-23 10:00 UTC, potsbo commented on Dockerfile
> +FROM alpine:3.4
Thanks

2017-01-23 10:03 UTC, potsbo commented
Do we have to separate repositories?
Just using quay build triggers doesn't solve the slow building issue?

2017-01-23 10:36 UTC, dtan4 commented
> Just using quay build triggers doesn't solve the slow building issue?

To use builder in Quay.io, we have to build binary or download binary in`Dockerfile`. This is not so good way...

2017-01-24 06:46 UTC, potsbo commented
> we have to build binary or download binary inDockerfile

I see that point.

But, since this project will not be updated on a daily basis, maybe taking a while to build in ci is not a problem for us.
How about considering to separate repos later, when it becomes a problem.

> I think that both latest and $(VERSION) should be prepared. latest points to the latest $(VERSION).

Do I have to push twice in two tags?

2017-01-24 09:31 UTC, dtan4 commented
OK, let's keep single repository now.

> Do I have to push twice in two tags?

Yes. `DOCKER_IMAGE_TAG=$TRAVIS_TAG make ci-docker-release` would work fine.

2017-01-24 09:37 UTC, potsbo commented
Added.

2017-01-24 10:40 UTC, dtan4 commented
LGTM 👍 
Are you sure that both `DOCKER_QUAY_USERNAME` and `DOCKER_QUAY_PASSWORD` were set?

2017-01-24 15:12 UTC, potsbo commented
Yes, It's been set.
<img width="1086" alt="screen shot 2017-01-25 at 0 10 35" src="https://cloud.githubusercontent.com/assets/7638553/22252835/d54390c6-e292-11e6-8023-665488915dab.png">

2017-01-25 01:39 UTC, dtan4 approved these changes

2017-01-25 01:39 UTC, dtan4 commented
OK, Now I merge this.

2017-01-25 01:39 UTC, merged