[WIP] Write readme
wantedly/github-username-converter pull request #39
Opened 2017-02-15 06:33 UTC by potsbo

## WHY

[Rich readme · Issue #37 · wantedly/developers-account-mapper](https://github.com/wantedly/developers-account-mapper/issues/37)

## WHAT

- [ ] Summary
- [ ] Description
- [ ] Usage
  - [ ] AWS configuration
  - [ ] Command usage
  - [ ] docker
- [ ] Install
- [ ] Contribution
- [ ] Author
- [ ] License

2017-02-15 06:58 UTC, potsbo commented
https://github.com/wantedly/developers-account-mapper/blob/potsbo/doc/README.md

2017-02-15 06:58 UTC, potsbo commented
@dtan4 Could you review this please

2017-02-15 07:18 UTC, dtan4 requested changes

2017-02-15 07:18 UTC, dtan4 commented on README.md
> +Especially abount Slack, developers-account-mapper is able to fetch Slack ID by Slack username and output it as a Slack mention format.
`abount` -> `about`

2017-02-15 07:18 UTC, dtan4 commented
Please add empty line {before,after} {headers/codeblocks}.

2017-02-15 07:22 UTC, potsbo commented on README.md
> +Especially abount Slack, developers-account-mapper is able to fetch Slack ID by Slack username and output it as a Slack mention format.
Fixed, thank you

2017-02-15 07:23 UTC, potsbo commented
Empty line added.
It's ready.

2017-02-15 07:27 UTC, dtan4 commented on README.md
> +In terraform, you can create the table with below.
`Terraform` is the correct spell.
https://www.terraform.io/

2017-02-15 07:34 UTC, potsbo commented on README.md
> +In terraform, you can create the table with below.
Thanks
And it should be a link.

2017-02-20 01:02 UTC, potsbo commented
@dtan4 Fixed

2017-02-20 01:36 UTC, dtan4 approved these changes

2017-02-20 01:36 UTC, dtan4 commented
LGTM 👍

2017-02-20 01:36 UTC, merged