Introduce Slack Integration
wantedly/github-username-converter pull request #7
Opened 2016-12-21 07:53 UTC by potsbo

## WHY

Developers need to map their Slack accounts and GitHub ones.

## WHAT

Add Slack account map ability
- [ ] Add Slack service to fetch SlackID(not username)
- [ ] Store Slack account information DynamoDB

## TEST
```console
potsbo@Shimpeis-MacBook-Pro-INS-% make && envchain wtd ./bin/developers-account-mapper register potsbo potsbo shimpei
go build -ldflags="-s -w -X \"main.Version=0.1.0\" -X \"main.Revision=ef04633\"" -o bin/developers-account-mapper
user "potsbo:@potsbo:<@shimpei:<CONSEALED>>" added.
potsbo@Shimpeis-MacBook-Pro-INS-% make && envchain wtd ./bin/developers-account-mapper list
make: `bin/developers-account-mapper' is up to date.
potsbo:@potsbo:<@shimpei:<CONSEALED>>
```

## NOTE

- Test is still not implemented, which has to be done

2016-12-21 10:07 UTC, dtan4 requested changes

2016-12-21 10:07 UTC, dtan4 commented on models/user.go
> +func (u *User) RetrieveSlackUserId() (*User, error) {
`u` is just a pointer, so this function need not to return itself again.

```go
func (u *User) RetrieveSlackUserId() error {
	// ...
	u.SetSlackUserId(nameIdMap[u.SlackUsername])
	return nil
}

2016-12-21 10:07 UTC, dtan4 commented on models/user.go
> +	u.SetSlackUserId(nameIdMap[u.SlackUsername])
```go
u.SlackUserId = nameIdMap[u.SlackUsername]
```

2016-12-21 10:07 UTC, dtan4 commented on services/slack_api.go
> +		id, _ := jq.String("members", strconv.Itoa(i), "id")
Please do not discard returned error as possible.

2016-12-21 10:07 UTC, dtan4 commented on models/user.go
> +		u.RetrieveSlackUserId()
Please catch error here.

2016-12-27 01:22 UTC, potsbo commented on models/user.go
> +func (u *User) RetrieveSlackUserId() (*User, error) {
Fixed

2016-12-27 01:30 UTC, potsbo commented on models/user.go
> +	u.SetSlackUserId(nameIdMap[u.SlackUsername])
Fixed

2016-12-27 01:32 UTC, potsbo commented on models/user.go
> +		u.RetrieveSlackUserId()
Rewrite to catch the error, but actually, I don't know how to handle this. Is that ok to return the error string?

2016-12-27 01:32 UTC, potsbo commented on services/slack_api.go
> +		id, _ := jq.String("members", strconv.Itoa(i), "id")
Fixed

2016-12-27 01:33 UTC, potsbo commented
@dtan4 
Thank you for the review.
And, this is my question: https://github.com/wantedly/developers-account-mapper/pull/7#discussion_r93889173 

### TEST
It works fine
```console
potsbo@magi-INS-% make && envchain wtd ./bin/developers-account-mapper register potsbo potsbo shimpei
make: `bin/developers-account-mapper' is up to date.
user "potsbo:@potsbo:<@shimpei:U2YBNNR24>" added.
```l

2016-12-27 04:12 UTC, dtan4 commented on models/user.go
> +		u.RetrieveSlackUserId()
I think `String()` should return both `string` and `error`.

```go
func (u *User) String() (string, error)
```

2016-12-27 07:00 UTC, potsbo commented on models/user.go
> +		u.RetrieveSlackUserId()
String is implicitly called here
`fmt.Printf("user %q added.\n", user)`
And, this seems to cause
```console
potsbo@magi-INS-% make && envchain wtd ./bin/developers-account-mapper register potsbo potsbo shimpei
go build -ldflags="-s -w -X \"main.Version=0.1.0\" -X \"main.Revision=8c5a955\"" -o bin/developers-account-mapper
# github.com/wantedly/developers-account-mapper/models
../../../../.go/src/github.com/wantedly/developers-account-mapper/models/user.go:40: cannot use nil as type string in return argument
make: *** [bin/developers-account-mapper] Error 2
```

I'm not 100% sure, though, maybe String should not return anything but a `string`.
Or, do you think we should assign like doing `str, err := user.String` and handle it?

2016-12-27 08:54 UTC, dtan4 approved these changes

2016-12-27 08:55 UTC, dtan4 commented
LGTM 👍

2016-12-27 08:55 UTC, merged

2016-12-27 09:04 UTC, potsbo commented
@dtan4 I need comment for https://github.com/wantedly/developers-account-mapper/pull/7#discussion_r93901791
it's failing

2016-12-27 09:21 UTC, dtan4 commented on models/user.go
> +		u.RetrieveSlackUserId()
> Or, do you think we should assign like doing str, err := user.String and handle it?

You should do so, or remove calling `RetrieveSlackUserId` in `String()`.

2016-12-27 09:21 UTC, dtan4 commented
Sorry, I missed that comment 😢